resource_test:
    resource: "@ResourceTestBundle/Resources/config/routing.yml"
    prefix:   /test
resource_user:
    resource: "@ResourceUserBundle/Resources/config/routing.yml"
    prefix:   /
resource_logged_area:
    resource: "@ResourceLoggedControllerBundle/Resources/config/routing.yml"
    prefix:   /logged-area
