resource_web_security:
    resource: "@ResourceWebSecurityBundle/Resources/config/routing.yml"
    prefix:   /

resource_user:
    resource: "@ResourceUserBundle/Resources/config/routing.yml"
    prefix:   /
resource_logged_area:
    resource: "@ResourceLoggedControllerBundle/Resources/config/routing.yml"
    prefix:   /logged-area
