resource_user:
    resource: "@ResourceUserBundle/Resources/config/routing.yml"
    prefix:   /

resource_security:
    resource: "@ResourceSecurityBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
