parameters:
    security.encoders.iterations : 2
security:
    providers:
         my_mongo_provider:
             mongodb: {class: Resource\Bundle\UserBundle\Document\User }
    firewalls:
        wsse_secured:
            pattern:   /logged-area/.*
            wsse:      true
    encoders:
        Resource\Bundle\UserBundle\Document\User:
            id : security.encoder.custom
