security:
    providers:
         my_mongo_provider:
             mongodb: {class: Resource\Bundle\UserBundle\Document\User }
    firewalls:
        wsse_secured:
            pattern:   /api/.*
            wsse:      true
    encoders:
        Resource\Bundle\UserBundle\Document\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       0
