security:
    providers:
         my_mongo_provider:
            mongodb: {class: Resource\Bundle\UserBundel\Document\User, property: username}
    firewalls:
        wsse_secured:
            pattern:   /api/.*
            wsse:      true

