# app/config/config.yml (or inside your services.yml)
services:
    demo.tokens.action_listener:
        class: Acme\DemoBundle\EventListener\TokenListener
        arguments: [ %tokens% ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }