services:
    listener.controller.request:
        class: Resource\Bundle\ListenerBundle\Listener\Controller\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
