services:
    listener.controller.request:
        class: Resource\Bundle\ListenerBundle\Listener\Controller\RequestListener
        arguments : [@response.formater.service]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    kernel.listener.api_exception_login:
        class: Resource\Bundle\ListenerBundle\Listener\ExceptionListener
        arguments: [@kernel,@response.formater.service]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    report.listener:
        class: Resource\Bundle\ListenerBundle\Doctrine\User
        arguments: [@security.encoder.custom]
        tags:
            - { name: doctrine_mongodb.odm.event_listener , event: prePersist }
    report.listener2:
        class: Resource\Bundle\ListenerBundle\Doctrine\User
        arguments: [@security.encoder.custom]
        tags:
            - { name: doctrine_mongodb.odm.event_listener , event: preUpdate }

    response.formater.service:
        class: Resource\Bundle\ListenerBundle\Services\ResponseFormaterService
