services:
  wsse.security.authentication.provider:
    class:  Resource\Bundle\SecurityBundle\Authentication\Provider\WsseProvider
    arguments: ['', %kernel.cache_dir%/security/nonces]

  wsse.security.authentication.listener:
    class:  Resource\Bundle\SecurityBundle\Security\Firewall\WsseListener
    arguments: [@security.context, @security.authentication.manager]
  security.encoder.custom:
    class: Resource\Bundle\SecurityBundle\Password\CustomEncoder
    arguments: [2]

