user_subscribe:
    path:     /subscribe
    defaults: { _controller: ResourceUserBundle:User:subscribe }
user_salt:
    path:     /salt
    defaults: { _controller: ResourceUserBundle:User:salt }
user_exists:
    path:     /exists
    defaults: { _controller: ResourceUserBundle:User:exists }
content_add:
    path:     /logged-area/add
    defaults: { _controller: ResourceUserBundle:Resource:add }
content_add_todo_remove:
    path:     /add
    defaults: { _controller: ResourceUserBundle:Resource:add }
content_search:
    path:     /logged-area/search
    defaults: { _controller: ResourceUserBundle:Resource:search}
search_hashtag:
    path:     /logged-area/hashtag
    defaults: { _controller: ResourceUserBundle:Search:hashtag}
todo_delete:
    path:     /hashtag
    defaults: { _controller: ResourceUserBundle:Search:hashtag}
search_my_hashtag:
    path:     /logged-area/hashtag/mine
    defaults: { _controller: ResourceUserBundle:Search:myhashtag}
update_my_hashtag:
    path:     /logged-area/hashtag/update
    defaults: { _controller: ResourceUserBundle:Search:updateSearch}





