Resource\Bundle\UserBundle\Document\User:
    constraints:
        - Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique:
             fields: email
    properties:
        username:
            - NotBlank: ~
        email:
            - Email: ~
            - NotBlank: ~
        password: 
            - NotBlank: ~
        password2:
            - NotBlank: ~
    getters:
        passwordEquals:
            - "True": {message: "Les deux mots de passe ne sont pas identiques "}
    
