#!/usr/bin/env php
<?php
// app/receiver

use Resource\Shell\ReceiverCommand;
use Symfony\Bundle\FrameworkBundle\Console\Application; 

include(__DIR__ . '/../vendor/autoload.php');

$application = new Application();
$application->add(new ReceiverCommand());
$application->run();
